# Generated by Django 5.2.7 on 2026-02-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_group_id_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_events', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GroupStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_students', models.IntegerField(default=0)),
                ('average_attendance', models.FloatField(default=0.0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.group')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
