# Generated by Django 6.0.1 on 2026-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.CharField(choices=[('yes', 'Р–РёРІС‘С‚ РІ РѕР±С‰РµР¶РёС‚РёРё'), ('no', 'РќРµ Р¶РёРІС‘С‚ РІ РѕР±С‰РµР¶РёС‚РёРё')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'РњР°Р»СЊС‡РёРє'), ('female', 'Р”РµРІРѕС‡РєР°')], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
