# Generated by Django 6.0.1 on 2026-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', 'name']},
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[('LLD', 'LLD'), ('1', '1 course'), ('2', '2 course'), ('3', '3 course'), ('4', '4 course')], default='LLD', max_length=3),
        ),
    ]
