# Generated by Django 6.0.1 on 2026-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('LLD', 'LLD'), ('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс')], max_length=10)),
            ],
            options={
                'ordering': ['course', 'name'],
                'unique_together': {('name', 'course')},
            },
        ),
    ]
