# Generated by Django 5.2.7 on 2026-02-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0002_alter_event_id'),
        ('students', '0002_alter_group_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-marked_at']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует'), ('late', 'Опоздал'), ('excused', 'Уважительная причина')], default='present', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'event')},
        ),
    ]
